const cells = 
[
  { word: 'DEVINER', x: 2, y: 4, direction: 'vertical', definition: 'Façon de trouver les objectifs', def_pos: 'ortho' },
  { word: 'MANEL', x: 2, y: 6, direction: 'vertical', definition: 'La Queen', def_pos: 'ortho' },
  { word: 'IDE', x: 2, y: 7, direction: 'vertical', definition: 'Pour coder', def_pos: 'ortho' },
  { word: 'GAB', x: 1, y: 9, direction: 'horizontal', definition: 'Il mange de la bière', def_pos: 'ortho' },
  { word: 'GN', x: 1, y: 9, direction: 'vertical', definition: "La Cocon d'Ezio en est un", def_pos: 'diagonale' },
  { word: 'PR', x: 2, y: 12, direction: 'vertical', definition: 'Pull request', def_pos: 'ortho' },
  { word: 'ALHADADE', x: 2, y: 13, direction: 'vertical', definition: 'Allégorie de la Street-cred', def_pos: 'ortho' },
  { word: 'NY', x: 2, y: 14, direction: 'vertical', definition: 'La ville des sales', def_pos: 'ortho' },
  { word: 'EM', x: 2, y: 16, direction: 'vertical', definition: 'Engineering manager', def_pos: 'ortho' },
  { word: 'JM', x: 1, y: 17, direction: 'vertical', definition: 'CEO par intérim', def_pos: 'diagonale' },
  { word: 'ID', x: 2, y: 18, direction: 'vertical', definition: "Identifiant d'une mention", def_pos: 'ortho' },
  { word: 'EAU', x: 2, y: 19, direction: 'vertical', definition: "Aurait permis d'éviter des gueules de bois pendant les offices days", def_pos: 'ortho' },
  { word: 'CHARLES', x: 2, y: 21, direction: 'vertical', definition: 'Chopé en train de choper dans les sous-sol', def_pos: 'ortho' },
  { word: 'MAXIME', x: 2, y: 23, direction: 'vertical', definition: 'A dormi pendant le OUAM', def_pos: 'ortho' },
  { word: 'EPIC', x: 2, y: 25, direction: 'vertical', definition: 'Grosse tâche', def_pos: 'ortho' },
  { word: 'LIEBE', x: 2, y: 26, direction: 'vertical', definition: '2€ la débauche', def_pos: 'ortho' },
  { word: 'RUPTURECONVENTIONNELLE', separateur: 6, x: 3, y: 2, direction: 'vertical', definition: 'Graal pour mentionos', def_pos: 'ortho' },
  { word: 'DAMIEN', x: 2, y: 4, direction: 'horizontal', definition: 'Toujours en short', def_pos: 'ortho' },
  { word: 'CAMILLE', x: 3, y: 10, direction: 'vertical', definition: 'Fière sudiste', def_pos: 'ortho' },
  { word: 'PANDEMIE', x: 2, y: 12, direction: 'horizontal', definition: "Période d'arrivée d'Adèle", def_pos: 'ortho' },
  { word: 'C', x: 2, y: 21, direction: 'horizontal', definition: "A Mention, certains programment avec, d'autres se la mettent dans le pif", def_pos: 'ortho' },
  { word: 'MAEL', x: 2, y: 23, direction: 'horizontal', definition: 'Lepetit frangin', def_pos: 'ortho' },
  { word: 'RUE', x: 3, y: 2, direction: 'horizontal', definition: 'Druot en est une', def_pos: 'ortho' },
  { word: 'AD', x: 3, y: 6, direction: 'horizontal', definition: 'Publicité anglaise', def_pos: 'ortho' },
  { word: 'AM', x: 4, y: 5, direction: 'vertical', definition: 'Moitié de la journée où Tanguy est bougon', def_pos: 'ortho' },
  { word: 'SLIP', x: 4, y: 8, direction: 'vertical', definition: 'De bain, Gab en a une très belle collection !', def_pos: 'ortho' },
  { word: 'CARLY', x: 3, y: 10, direction: 'horizontal', definition: 'Alter ego de Janet', def_pos: 'ortho' },
  { word: 'CS', x: 4, y: 15, direction: 'vertical', definition: 'Pas mal de mentionos y jouent en ligne ensemble', def_pos: 'ortho' },
  { word: 'DASH', x: 3, y: 18, direction: 'horizontal', definition: "Page d'accueil développée ... à moitié", def_pos: 'ortho' },
  { word: 'VANESSA', x: 4, y: 4, direction: 'horizontal', definition: 'Elle nexiste que pour Quentin', def_pos: 'ortho' },
  { word: 'ACIER', x: 5, y: 11, direction: 'vertical', definition: 'Les mollets de Damien en sont fait', def_pos: 'ortho' },
  { word: 'ITT', x: 5, y: 14, direction: 'vertical', definition: 'Quand on peut plus bosser', def_pos: 'ortho' },
  { word: 'AGORAPULSE', x: 5, y: 16, direction: 'vertical', definition: "Pas sûr qu'ils aient fait une bonne affaire", def_pos: 'ortho' },
  { word: 'NAN', x: 5, y: 17, direction: 'vertical', definition: "Pas un nombre", def_pos: 'ortho' },
  { word: 'X', x: 4, y: 23, direction: 'horizontal', definition: 'Nouveau Twitter', def_pos: 'ortho' },
  { word: 'IE', x: 4, y: 25, direction: 'horizontal', definition: "Mention ne le supporte pas", def_pos: 'ortho' },
  { word: 'PRIME', x: 5, y: 2, direction: 'horizontal', definition: 'Bonus pour une vente', def_pos: 'ortho' },
  { word: 'MALAISANT', x: 5, y: 10, direction: 'horizontal', definition: 'Les OUAM de JG', def_pos: 'ortho' },
  { word: 'ORDI', x: 5, y: 20, direction: 'horizontal', definition: 'Support pour nos nights karaoké', def_pos: 'ortho' },
  { word: 'CB', x: 5, y: 25, direction: 'horizontal', definition: "Alhadade la sortait pour l'Afterwork", def_pos: 'ortho' },
  { word: 'LATINAS', x: 6, y: 24, direction: 'vertical', definition: "Elles supportent la moitié de l'Amérique", def_pos: 'ortho' },
  { word: 'AFTERWORKS', x: 7, y: 7, direction: 'vertical', definition: 'Jeudi soir', def_pos: 'ortho' },
  { word: 'IC', x: 6, y: 10, direction: 'horizontal', definition: 'Ancien Quick Charts', def_pos: 'ortho' },
  { word: 'DT', x: 6, y: 13, direction: 'horizontal', definition: "Le poste d'Arnaud, en français", def_pos: 'ortho' },
  { word: 'CAM', x: 7, y: 12, direction: 'vertical', definition: 'Une petite pote', def_pos: 'ortho' },
  { word: 'GABY', x: 6, y: 16, direction: 'horizontal', definition: 'La sœur de Carmen', def_pos: 'ortho' },
  { word: 'IOTA', x: 7, y: 15, direction: 'vertical', definition: 'Petite quantité, comme les bénéfices de Mention', def_pos: 'ortho' },
  { word: 'BAN', x: 7, y: 20, direction: 'vertical', definition: 'blocage d’un spam', def_pos: 'ortho' },
  { word: 'ML', x: 6, y: 23, direction: 'horizontal', definition: 'Maîtrise de Bryan', def_pos: 'ortho' },
  { word: 'RAI', x: 7, y: 22, direction: 'vertical', definition: 'Le logo Mention en a 5', def_pos: 'ortho' },
  { word: 'USER', x: 7, y: 2, direction: 'horizontal', definition: 'La squad fourre-tout', def_pos: 'ortho' },
  { word: 'APPLICATIONS', x: 7, y: 7, direction: 'horizontal', definition: 'Les bébés morts de Seb et Alex', def_pos: 'ortho' },
  { word: 'IO', x: 8, y: 6, direction: 'vertical', definition: 'Entrée/Sortie', def_pos: 'ortho' },
  { word: 'BEREAL', x: 7, y: 20, direction: 'horizontal', definition: 'Réseau social pour mentionos', def_pos: 'ortho' },
  { word: 'JOUFFROY', x: 8, y: 19, direction: 'vertical', definition: 'Il est de passage', def_pos: 'ortho' },
  { word: 'MAT', x: 8, y: 26, direction: 'vertical', definition: 'Celui qui a fait 410', def_pos: 'ortho' },
  { word: 'CEO', x: 9, y: 1, direction: 'horizontal', definition: "Antoine l'incompétant", def_pos: 'diagonale' },
  { word: 'OOO', x: 9, y: 3, direction: 'vertical', definition: 'Pas en train de bosser', def_pos: 'ortho' },
  { word: 'IFS', x: 8, y: 6, direction: 'horizontal', definition: 'Conditions multiples dans le code', def_pos: 'ortho' },
  { word: 'HAMMAMET', x: 9, y: 5, direction: 'vertical', definition: 'Dernière retraite', def_pos: 'ortho' },
  { word: 'LEAD', x: 8, y: 10, direction: 'horizontal', definition: 'Chouchou des Sales', def_pos: 'ortho' },
  { word: 'FLAMMEDOUDOUNE', separateur: 5, x: 9, y: 9, direction: 'vertical', definition: 'pour invoquer Astrid', def_pos: 'ortho' },
  { word: 'OR', x: 8, y: 15, direction: 'horizontal', definition: "A Mention, on roule pas dessus", def_pos: 'ortho' },
  { word: 'JASA', x: 8, y: 19, direction: 'horizontal', definition: "A Mention, ça bitcha en français (ça)", def_pos: 'ortho' },
  { word: 'TOM', x: 8, y: 24, direction: 'horizontal', definition: 'Prêtre lubrique', def_pos: 'ortho' },
  { word: 'HOT', x: 9, y: 5, direction: 'horizontal', definition: 'Astrid en policière', def_pos: 'ortho' },
  { word: 'FERMENTATION', x: 9, y: 9, direction: 'horizontal', definition: "Processus au sous-sol d'Antoine", def_pos: 'ortho' },
  { word: 'IBIZA', x: 9, y: 22, direction: 'horizontal', definition: 'Deuxième retraite', def_pos: 'ortho' },
  { word: 'VISAS', x: 10, y: 21, direction: 'vertical', definition: "Sans, Sophia et Patricia n'ont pas pu venir à la retraite", def_pos: 'ortho' },
  { word: "CODA", x: 10, y: 2, direction: "horizontal", definition: "Ecrivit du code", def_pos: 'ortho' },
  { word: "ZOO", x: 11, y: 1, direction: "horizontal", definition: "Open space de la tech", def_pos: 'diagonale' },
  { word: "K", x: 11, y: 10, direction: "vertical", definition: "DJ de Qualité (Le)", def_pos: 'ortho' },
  { word: "EN", x: 11, y: 11, direction: "vertical", definition: "Langue principale de l'app", def_pos: 'ortho' },
  { word: "CHARDONNAY", x: 11, y: 12, direction: "vertical", definition: "Amilah ne sait pas le reconnaître", def_pos: 'ortho' },
  { word: "HS", x: 11, y: 13, direction: "vertical", definition: "Etat des néons après la soirée d'Halloween", def_pos: 'ortho' },
  { word: "AP", x: 10, y: 15, direction: "horizontal", definition: "AgoraPulse TL;DR", def_pos: 'ortho' },
  { word: "LIKE", x: 11, y: 25, direction: "vertical", definition: "On traque son nombre dans les reports", def_pos: 'ortho' },
  { word: "MARRAKECH", x: 11, y: 5, direction: "horizontal", definition: "Première retraite", def_pos: 'ortho' },
  { word: "TONYPORNOPS", separateur: 3, x: 12, y: 14, direction: "vertical", definition: "Il a un vinyle en son nom. PS : aller streamer sur spotify", def_pos: 'ortho' },
  { word: "UNOFFICIAL", x: 11, y: 16, direction: "horizontal", definition: "Retreat fauchée", def_pos: 'ortho' },
  { word: "PM", x: 12, y: 4, direction: "horizontal", definition: "Elle pratique la boxe de gonzesse", def_pos: 'ortho' },
  { word: "NHST", x: 12, y: 11, direction: "horizontal", definition: "Ils jettent l'argent par les fenêtres", def_pos: 'ortho' },
  { word: "AI", x: 13, y: 18, direction: "vertical", definition: "Used by augmentors", def_pos: 'ortho' },
  { word: "SIF", x: 12, y: 24, direction: "horizontal", definition: "Celui de Xavier est toujours impeccable", def_pos: 'ortho' },
  { word: "DEV", x: 14, y: 1, direction: "horizontal", definition: "Il pue et se plaint", def_pos: 'ortho' },
  { word: "OPS", x: 13, y: 14, direction: "horizontal", definition: "Sacré architectes", def_pos: 'ortho' },
  { word: "ARNAUD", x: 13, y: 18, direction: "horizontal", definition: "Dieu du code", def_pos: 'ortho' },
  { word: "ZENROOM", x: 14, y: 17, direction: "vertical", definition: "On s'y fait virer", def_pos: 'ortho' },
  { word: "MARKETER", x: 14, y: 5, direction: "horizontal", definition: "Action de vendre un produit qu’on ne comprend pas nous même", def_pos: 'ortho' },
  { word: "LISA", x: 15, y: 4, direction: "vertical", definition: "Elle habite au Mex'iik", def_pos: 'ortho' },
  { word: "EZIO", x: 14, y: 16, direction: "horizontal", definition: "Allégorie de maladresse", def_pos: 'ortho' },
  { word: "TAG", x: 15, y: 15, direction: "vertical", definition: "Feature de Mention", def_pos: 'ortho' },
  { word: "BORDEL", x: 15, y: 22, direction: "vertical", definition: "Joyeux chaos des afterworks", def_pos: 'ortho' },
  { word: "DECLIC", x: 15, y: 24, direction: "vertical", definition: "Déclencheur pour démissionner", def_pos: 'ortho' },
  { word: "EP", x: 16, y: 8, direction: "vertical", definition: "Amidst Two Oceans", def_pos: 'ortho' },
  { word: "JD", x: 15, y: 11, direction: "horizontal", definition: "Record de temps en Réunion", def_pos: 'ortho' },
  { word: "YT", x: 15, y: 14, direction: "horizontal", definition: "Petite source de Mention", def_pos: 'ortho' },
  { word: "YO", x: 15, y: 19, direction: "horizontal", definition: "Bonjour dans l'open space", def_pos: 'ortho' },
  { word: "XAVIER", x: 16, y: 26, direction: "vertical", definition: "Professeur de débauche", def_pos: 'ortho' },
  { word: "TOIT", x: 16, y: 2, direction: "horizontal", definition: "Valérie en est tombé", def_pos: 'ortho' },
  { word: "SEO", x: 16, y: 7, direction: "horizontal", definition: "Sigle du bon référencement", def_pos: 'ortho' },
  { word: "COMPAGNE", x: 16, y: 11, direction: "horizontal", definition: "Hagera pour Arnaud", def_pos: 'ortho' },
  { word: "ALCOLO", x: 17, y: 19, direction: "vertical", definition: "Peut se dire de la plus part des mentionos", def_pos: 'ortho' },
  { word: "JOYEUX", x: 16, y: 21, direction: "horizontal", definition: "Des cafés pas comme les autres", def_pos: 'ortho' },
  { word: "PUB", x: 17, y: 8, direction: "horizontal", definition: "La petite squad de Tanguy", def_pos: 'ortho' },
  { word: "SEDUCTEURS", x: 18, y: 7, direction: "vertical", definition: "Charles, Gab, Hugo", def_pos: 'ortho' },
  { word: "OG", x: 17, y: 14, direction: "horizontal", definition: "Alhadade", def_pos: 'ortho' },
  { word: "SPOTIFY", x: 18, y: 21, direction: "vertical", definition: "Sa suppression était la goutte d'eau pour Etienne", def_pos: 'ortho' },
  { word: "OTAKUS", x: 18, y: 2, direction: "horizontal", definition: "Fans du Japon comme Céline", def_pos: 'ortho' },
  { word: "SD", x: 18, y: 21, direction: "horizontal", definition: "Paraphe de souquid", def_pos: 'ortho' },
  { word: "ANDROID", x: 20, y: 1, direction: "horizontal", definition: "Une des apps mobiles de Mention", def_pos: 'diagonale' },
  { word: "RICE", x: 20, y: 4, direction: "vertical", definition: "Metric au doigt mouillé", def_pos: 'ortho' },
  { word: "VELO", x: 19, y: 6, direction: "horizontal", definition: "Arnaud peut en parler des heures", def_pos: 'ortho' },
  { word: "MAGNETOSCOPE", x: 19, y: 11, direction: "horizontal", definition: "On peut y boire, baiser et dormir", def_pos: 'ortho' },
  { word: "VHS", x: 20, y: 25, direction: "vertical", definition: "Tapisserie du Magnéto", def_pos: 'ortho' },
  { word: "US", x: 20, y: 9, direction: "horizontal", definition: "La moitié du marché s'y trouve", def_pos: 'ortho' },
  { word: "WE", x: 21, y: 11, direction: "vertical", definition: "Petite attente de la semaine", def_pos: 'ortho' },
  { word: "CELINE", x: 21, y: 15, direction: "vertical", definition: "Frontos chez Insights", def_pos: 'ortho' },
  { word: "OL", x: 20, y: 21, direction: "horizontal", definition: "Club de foot de chez Manon", def_pos: 'ortho' },
  { word: "DUEL", x: 21, y: 23, direction: "vertical", definition: "Rap Battle", def_pos: 'ortho' },
  { word: 'MOUETTES', x: 22, y: 10, direction: 'vertical', definition: 'Elles ont pieds', def_pos: 'ortho' },
  { word: 'PC', x: 21, y: 14, direction: 'horizontal', definition: 'Toujours à poil', def_pos: 'ortho' },
  { word: 'TWEET', x: 22, y: 13, direction: 'vertical', definition: 'Ils coûtent cher à récupérer', def_pos: 'ortho' },
  { word: 'OVH', x: 22, y: 17, direction: 'vertical', definition: 'Ils hébergent nos serveurs', def_pos: 'ortho' },
  { word: 'QUENTIN', x: 22, y: 22, direction: 'vertical', definition: 'Askip, il a faillit racheter Mention', def_pos: 'ortho' },
  { word: 'HR', x: 21, y: 25, direction: 'horizontal', definition: "Privacy wasn't a strong point of this service", def_pos: 'ortho' },
  { word: 'ELLES', x: 22, y: 24, direction: 'vertical', definition: 'Pronom pour désigner les Account Manager (et Rodrigo)', def_pos: 'ortho' },
  { word: 'LICENCIEMENTSECONOMIQUES', separateur: 12, x: 22, y: 2, direction: 'horizontal', definition: 'Ils ont coupé dans le lard à trois reprises', def_pos: 'ortho' },
  { word: 'ASTRID', x: 23, y: 26, direction: 'vertical', definition: 'La plus cagole des PM', def_pos: 'ortho' },
  { word: 'YES', x: 24, y: 1, direction: 'horizontal', definition: 'Philosophie de vie de Bière-Chanel', def_pos: 'ortho' },
  { word: 'SOPHIA', x: 24, y: 3, direction: 'vertical', definition: 'en retard même à son propre anniversaire', def_pos: 'ortho' },
  { word: 'TT', x: 24, y: 11, direction: 'vertical', definition: 'Principal avantage à Mention', def_pos: 'ortho' },
  { word: 'FUEL', x: 23, y: 21, direction: 'horizontal', definition: "Richesse d'NHST", def_pos: 'ortho' },
  { word: 'OFFICE', x: 24, y: 20, direction: 'vertical', definition: 'On se retrouve tous pendant ses jours', def_pos: 'ortho' },
  { word: 'DEBOUT', x: 24, y: 6, direction: 'horizontal', definition: 'Position des daily, by the book', def_pos: 'ortho' },
  { word: 'SQUAD', x: 25, y: 5, direction: 'vertical', definition: 'Equipe de mentionos', def_pos: 'ortho' },
  { word: 'ISSOU', x: 25, y: 12, direction: 'vertical', definition: "Expression de El Risitas populaire chez les geek de Mention", def_pos: 'ortho' },
  { word: 'VOYELLES', x: 24, y: 19, direction: 'horizontal', definition: 'Quentin les perds souvent', def_pos: 'ortho' },
  { word: 'DATA', x: 25, y: 18, direction: 'vertical', definition: 'Le royaume de Xavier', def_pos: 'ortho' },
  { word: 'OBSCUR', x: 25, y: 3, direction: 'horizontal', definition: 'Les règles autour de workspaces', def_pos: 'ortho' },
  { word: 'ETIENNE', x: 25, y: 10, direction: 'horizontal', definition: 'Titi sans Grosminet', def_pos: 'ortho' },
  { word: 'TATE', x: 26, y: 17, direction: 'vertical', definition: "Lucien s'est fait virer pour l'avoir fait", def_pos: 'ortho' },
  { word: 'FR', x: 26, y: 19, direction: 'vertical', definition: 'Deuxième langue de l\'application', def_pos: 'ortho' },
  { word: 'IA', x: 26, y: 23, direction: 'vertical', definition: "Alert Overview s'en sert", def_pos: 'ortho' },
  { word: 'CS', x: 27, y: 2, direction: 'vertical', definition: 'En charge de gérer les Karen', def_pos: 'ortho' },
  { word: 'ST', x: 26, y: 12, direction: 'horizontal', definition: "Quentin le porte en nom mais n'en est pas un", def_pos: 'ortho' },
  { word: 'SQL', x: 27, y: 14, direction: 'vertical', definition: "Langage d'XPLR", def_pos: 'ortho' },
  { word: 'TAFF', x: 26, y: 17, direction: 'horizontal', definition: "A la fin à Mention on en faisait plus trop", def_pos: 'ortho' },
  { word: 'TISER', x: 26, y: 22, direction: 'horizontal', definition: "Activité préférée des mentionos", def_pos: 'ortho' },
  { word: 'CHAUSSETTES', x: 27, y: 2, direction: 'horizontal', definition: "Florian ne les mets pas aux pieds", def_pos: 'ortho' },
  { word: 'PATRICIA', x: 27, y: 16, direction: 'horizontal', definition: "Patty pour les intimes", def_pos: 'ortho' },
  { word: 'UI', x: 28, y: 24, direction: 'vertical', definition: "Old school surtout sur le feed", def_pos: 'ortho' },
  { word: 'SF', x: 28, y: 25, direction: 'vertical', definition: "Framework du backend", def_pos: 'ortho' },
  { word: 'SI', x: 28, y: 2, direction: 'horizontal', definition: "La charge des alternants d'Antoine", def_pos: 'ortho' },
  { word: 'QUOTA', x: 28, y: 14, direction: 'horizontal', definition: "Paramétrable depuis Chargebee", def_pos: 'ortho' },
  { word: 'USD', x: 28, y: 24, direction: 'horizontal', definition: "Pour acheter Mention aux US", def_pos: 'ortho' },
  { word: 'AUDREY', x: 29, y: 3, direction: 'horizontal', definition: "son arrivée est corrélée avec la fin de mention", def_pos: 'ortho' },
  { word: 'SOUPLINE', x: 29, y: 10, direction: 'horizontal', definition: "Lissage de Pierre", def_pos: 'ortho' },
  { word: 'BEN', x: 29, y: 19, direction: 'horizontal', definition: "Directeur mal-aimé du Marketing", def_pos: 'ortho' },
  { word: 'GIF', x: 29, y: 23, direction: 'horizontal', definition: "Fichier animé qui enflammait notre Slack", def_pos: 'ortho' }
]

export default cells;