const cells = [
  { word: 'DEVINER', x: 2, y: 4, position: 'vertical', definition: 'Façon de trouver les objectifs' },
  { word: 'MANEL', x: 2, y: 6, direction: 'vertical', definition: 'La Queen' },
  { word: 'IDE', x: 2, y: 7, direction: 'vertical', definition: 'Pour coder' },
  { word: 'GAB', x: 1, y: 9, direction: 'horizontal', definition: 'Il mange de la bière' },
  { word: 'GN', x: 1, y: 9, direction: 'vertical', definition: "La Cocon d'Ezio en est un" },
  { word: 'PR', x: 2, y: 12, direction: 'vertical', definition: 'Pull request' },
  { word: 'ALHADADE', x: 2, y: 13, direction: 'vertical', definition: 'Allégorie de la Street-cred' },
  { word: 'NY', x: 2, y: 14, direction: 'vertical', definition: 'La ville des sales' },
  { word: 'EM', x: 2, y: 16, direction: 'vertical', definition: 'Engineering manager' },
  { word: 'JM', x: 1, y: 17, direction: 'vertical', definition: 'CEO par intérim' },
  { word: 'ID', x: 2, y: 18, direction: 'vertical', definition: "Identifiant d'une mention" },
  { word: 'EAU', x: 2, y: 19, direction: 'vertical', definition: "Aurait permis d'éviter des gueules de bois pendant les offices days" },
  { word: 'CHARLES', x: 2, y: 21, direction: 'vertical', definition: 'Chopé en train de choper dans les sous-sol' },
  { word: 'MAXIME', x: 2, y: 23, direction: 'vertical', definition: 'A dormi pendant le OUAM' },
  { word: 'EPIC', x: 2, y: 25, direction: 'vertical', definition: 'Grosse tâche' },
  { word: 'LIEBE', x: 2, y: 26, direction: 'vertical', definition: '2€ la débauche' },
  { word: 'RUPTURECONVENTIONNELLE', x: 3, y: 2, direction: 'vertical', definition: 'Graal pour mentionos' },
  { word: 'DAMIEN', x: 2, y: 4, direction: 'horizontal', definition: 'Toujours en short' },
  { word: 'CAMILLE', x: 3, y: 10, direction: 'vertical', definition: 'Fière sudiste' },
  { word: 'PANDEMIE', x: 2, y: 12, direction: 'horizontal', definition: "Période d'arrivée d'Adèle" },
  { word: 'C', x: 2, y: 21, direction: 'horizontal', definition: "A Mention, certains programment avec, d'autres se la mettent dans le pif" },
  { word: 'MAEL', x: 2, y: 23, direction: 'horizontal', definition: 'Lepetit frangin' },
  { word: 'RUE', x: 3, y: 2, direction: 'horizontal', definition: 'Druot en est une' },
  { word: 'AD', x: 3, y: 6, direction: 'horizontal', definition: 'Publicité anglaise' },
  { word: 'AM', x: 4, y: 5, direction: 'vertical', definition: 'Moitié de la journée où Tanguy est bougon' },
  { word: 'SLIP', x: 4, y: 8, direction: 'vertical', definition: 'De bain, Gab en a une très belle collection !' },
  { word: 'CARLY', x: 3, y: 10, direction: 'horizontal', definition: 'Alter ego de Janet' },
  { word: 'CS', x: 4, y: 15, direction: 'vertical', definition: 'Pas mal de mentionos y jouent en ligne ensemble' },
  { word: 'DASH', x: 3, y: 18, direction: 'horizontal', definition: "Page d'accueil développée ... à moitié" },
  { word: 'VANESSA', x: 4, y: 4, direction: 'horizontal', definition: 'Elle nexiste que pour Quentin' },
  { word: 'ACIER', x: 5, y: 11, direction: 'vertical', definition: 'Les mollets de Damien en sont fait' },
  { word: 'ITT', x: 5, y: 14, direction: 'vertical', definition: 'Quand on peut plus bosser' },
  { word: 'AGORAPULSE', x: 5, y: 16, direction: 'vertical', definition: "Pas sûr qu'ils aient fait une bonne affaire" },
  { word: 'NAN', x: 5, y: 17, direction: 'vertical', definition: "Pas un nombre" },
  { word: 'X', x: 4, y: 23, direction: 'horizontal', definition: 'Nouveau Twitter' },
  { word: 'IE', x: 4, y: 25, direction: 'horizontal', definition: "Mention ne le supporte pas" },
  { word: 'PRIME', x: 5, y: 2, direction: 'horizontal', definition: 'Bonus pour une vente' },
  { word: 'MALAISANT', x: 5, y: 10, direction: 'horizontal', definition: 'Les OUAM de JG' },
  { word: 'ORDI', x: 5, y: 20, direction: 'horizontal', definition: 'Support pour nos nights karaoké' },
  { word: 'CB', x: 5, y: 25, direction: 'horizontal', definition: "Alhadade la sortait pour l'Afterwork" },
  { word: 'LATINAS', x: 6, y: 24, direction: 'vertical', definition: "Elles supportent la moitié de l'Amérique" },
  { word: 'AFTERWORKS', x: 7, y: 7, direction: 'vertical', definition: 'Jeudi soir' },
  { word: 'IC', x: 6, y: 10, direction: 'horizontal', definition: 'Ancien Quick Charts' },
  { word: 'DT', x: 6, y: 13, direction: 'horizontal', definition: "Le poste d'Arnaud, en français" },
  { word: 'CAM', x: 7, y: 12, direction: 'vertical', definition: 'Une petite pote' },
  { word: 'GABY', x: 6, y: 16, direction: 'horizontal', definition: 'La sœur de Carmen' },
  { word: 'IOTA', x: 7, y: 15, direction: 'vertical', definition: 'Petite quantité, comme les bénéfices de Mention' },
  { word: 'BAN', x: 7, y: 20, direction: 'vertical', definition: 'blocage d’un spam' },
  { word: 'ML', x: 6, y: 23, direction: 'horizontal', definition: 'Maîtrise de Bryan' },
  { word: 'RAI', x: 7, y: 22, direction: 'vertical', definition: 'Le logo Mention en a 5' },
  { word: 'USER', x: 7, y: 2, direction: 'horizontal', definition: 'La squad fourre-tout' },
  { word: 'APPLICATIONS', x: 7, y: 7, direction: 'horizontal', definition: 'Les bébés morts de Seb et Alex' },
  { word: 'I/O', x: 8, y: 6, direction: 'vertical', definition: 'Entrée/Sortie' },
  { word: 'BEREAL', x: 7, y: 20, direction: 'horizontal', definition: 'Réseau social pour mentionos' },
  { word: 'JOUFFROY', x: 8, y: 19, direction: 'vertical', definition: 'Il est de passage' },
  { word: 'MAT', x: 8, y: 26, direction: 'vertical', definition: 'Celui qui a fait 410' },
  { word: 'CEO', x: 9, y: 1, direction: 'horizontal', definition: "Antoine l'incompétant" },
  { word: 'OOO', x: 9, y: 3, direction: 'vertical', definition: 'Pas en train de bosser' },
  { word: 'IFS', x: 8, y: 6, direction: 'horizontal', definition: 'Conditions multiples dans le code' },
  { word: 'HAMMAMET', x: 9, y: 5, direction: 'vertical', definition: 'Dernière retraite' },
  { word: 'LEAD', x: 8, y: 10, direction: 'horizontal', definition: 'Chouchou des Sales' },
  { word: 'FLAMMEDOUDOUNE', x: 9, y: 9, direction: 'vertical', definition: 'pour invoquer Astrid' },
  { word: 'OR', x: 8, y: 15, direction: 'horizontal', definition: "A Mention, on roule pas dessus" },
  { word: 'JASA', x: 8, y: 19, direction: 'horizontal', definition: "A Mention, ça bitcha en français (ça)" },
  { word: 'TOM', x: 8, y: 24, direction: 'horizontal', definition: 'Prêtre lubrique' },
  { word: 'HOT', x: 9, y: 5, direction: 'horizontal', definition: 'Astrid en policière' },
  { word: 'FERMENTATION', x: 9, y: 9, direction: 'horizontal', definition: "Processus au sous-sol d'Antoine" },
  { word: 'IBIZA', x: 9, y: 22, direction: 'horizontal', definition: 'Deuxième retraite' },
  { word: 'VISAS', x: 10, y: 21, direction: 'vertical', definition: "Sans, Sophia et Patricia n'ont pas pu venir à la retraite" },
 { word: "CODA", x: 10, y: 2, direction: "horizontal", definition: "Ecrivit du code" },
{ word: "ZOO", x: 11, y: 1, direction: "horizontal", definition: "Open space de la tech" },
{ word: "K", x: 11, y: 10, direction: "vertical", definition: "DJ de Qualité (Le)" },
{ word: "EN", x: 11, y: 11, direction: "vertical", definition: "Langue principale de l'app" },
{ word: "CHARDONNAY", x: 11, y: 12, direction: "vertical", definition: "Amilah ne sait pas le reconnaître" },
{ word: "HS", x: 11, y: 13, direction: "vertical", definition: "Etat des néons après la soirée d'Halloween" },
{ word: "AP", x: 10, y: 15, direction: "horizontal", definition: "AgoraPulse TL;DR" },
{ word: "LIKE", x: 11, y: 25, direction: "vertical", definition: "On traque son nombre dans les reports" },
{ word: "MARRAKECH", x: 11, y: 5, direction: "horizontal", definition: "Première retraite" },
{ word: "TONYPORNOPS", x: 12, y: 14, direction: "vertical", definition: "Il a un vinyle en son nom PS : aller streamer sur spotify" },
{ word: "UNOFFICIAL", x: 11, y: 16, direction: "horizontal", definition: "Retreat fauchée" },
{ word: "PM", x: 12, y: 4, direction: "horizontal", definition: "Elle pratique la boxe de gonzesse" },
{ word: "NHST", x: 12, y: 11, direction: "horizontal", definition: "Ils jettent l'argent par les fenêtres" },
{ word: "AI", x: 13, y: 18, direction: "vertical", definition: "Used by augmentors" },
{ word: "SIF", x: 12, y: 24, direction: "horizontal", definition: "Celui de Xavier est toujours impeccable" },
{ word: "DEV", x: 14, y: 1, direction: "horizontal", definition: "Il pue et se plaint" },
{ word: "OPS", x: 13, y: 14, direction: "horizontal", definition: "Sacré architectes" },
{ word: "ARNAUD", x: 13, y: 18, direction: "horizontal", definition: "Dieu du code" },
{ word: "ZENROOM", x: 14, y: 17, direction: "vertical", definition: "on s'y fait virer" },
{ word: "MARKETER", x: 14, y: 5, direction: "horizontal", definition: "Action de vendre un produit qu’on ne comprend pas nous même" },
{ word: "LISA", x: 15, y: 4, direction: "vertical", definition: "Elle habite au Mex'iik" },
{ word: "EZIO", x: 14, y: 16, direction: "horizontal", definition: "Allégorie de maladresse" },
{ word: "TAG", x: 15, y: 15, direction: "vertical", definition: "Feature de Mention" },
{ word: "BORDEL", x: 15, y: 22, direction: "vertical", definition: "Joyeux chaos des afterworks" },
{ word: "DECLIC", x: 15, y: 24, direction: "vertical", definition: "Déclencheur pour démissionner" },
{ word: "EP", x: 16, y: 8, direction: "vertical", definition: "Amidst Two Oceans" },
{ word: "JD", x: 15, y: 11, direction: "horizontal", definition: "Record de temps en Réunion" },
{ word: "YT", x: 15, y: 14, direction: "horizontal", definition: "Petite source de Mention" },
{ word: "YO", x: 15, y: 19, direction: "horizontal", definition: "Bonjour dans l'open space" },
{ word: "XAVIER", x: 16, y: 26, direction: "vertical", definition: "Professeur de débauche" },
{ word: "TOIT", x: 16, y: 2, direction: "horizontal", definition: "Valérie en est tombé" },
{ word: "SEO", x: 16, y: 7, direction: "horizontal", definition: "Sigle du bon référencement" },
{ word: "COMPAGNE", x: 16, y: 11, direction: "horizontal", definition: "Hagera pour Arnaud" },
{ word: "ALCOLO", x: 17, y: 19, direction: "vertical", definition: "Peut se dire de la plus part des mentionos" },
{ word: "JOYEUX", x: 16, y: 21, direction: "horizontal", definition: "Des cafés pas comme les autres" },
{ word: "PUB", x: 17, y: 8, direction: "horizontal", definition: "La petite squad de Tanguy" },
{ word: "SEDUCTEURS", x: 18, y: 7, direction: "vertical", definition: "Charles, Gab, Hugo" },
{ word: "OG", x: 17, y: 14, direction: "horizontal", definition: "Alhadade" },
{ word: "SPOTIFY", x: 18, y: 21, direction: "vertical", definition: "Sa suppression était la goutte d'eau pour Etienne" },
{ word: "OTAKUS", x: 18, y: 2, direction: "horizontal", definition: "Fans du Japon comme Céline" },
{ word: "SD", x: 18, y: 21, direction: "horizontal", definition: "Paraphe de souquid" },
{ word: "ANDROID", x: 20, y: 1, direction: "horizontal", definition: "Une des apps mobiles de Mention" },
{ word: "RICE", x: 20, y: 4, direction: "vertical", definition: "Metric au doigt mouillé" },
{ word: "VELO", x: 19, y: 6, direction: "horizontal", definition: "Arnaud peut en parler des heures" },
{ word: "MAGNETOSCOPE", x: 19, y: 11, direction: "horizontal", definition: "On peut y boire, baiser et dormir" },
{ word: "VHS", x: 20, y: 25, direction: "vertical", definition: "Tapisserie du Magnéto" },
{ word: "US", x: 20, y: 9, direction: "horizontal", definition: "La moitié du marché s'y trouve" },
{ word: "WE", x: 21, y: 11, direction: "vertical", definition: "Petite attente de la semaine" },
{ word: "CELINE", x: 21, y: 15, direction: "vertical", definition: "Frontos chez Insights" },
{ word: "OL", x: 20, y: 21, direction: "horizontal", definition: "Club de foot de chez Manon" },
{ word: "DUEL", x: 21, y: 23, direction: "vertical", definition: "Rap Battle" },
{ word: 'MOUETTES', x: 22, y: 10, direction: 'vertical', definition: 'Elles ont pieds' },
{ word: 'PC', x: 21, y: 14, direction: 'horizontal', definition: 'Toujours à poil' },
{ word: 'TWEET', x: 22, y: 13, direction: 'vertical', definition: 'Ils coûtent cher à récupérer' },
{ word: 'OVH', x: 22, y: 17, direction: 'vertical', definition: 'Ils hébergent nos serveurs' },
{ word: 'QUENTIN', x: 22, y: 22, direction: 'vertical', definition: 'Askip, il a faillit racheter Mention' },
{ word: 'HR', x: 21, y: 24, direction: 'horizontal', definition: "Privacy wasn't a strong point of this service" },
{ word: 'ELLES', x: 22, y: 23, direction: 'vertical', definition: 'Pronom pour désigner les Account Manager (er Rodrigo)' },
{ word: 'LICENCIEMENTSECONOMIQUES', x: 22, y: 2, direction: 'horizontal', definition: 'Ils ont coupé dans le lard à trois reprises' },
{ word: 'ASTRID', x: 23, y: 26, direction: 'vertical', definition: 'La plus cagole des PM' },
{ word: 'YES', x: 24, y: 1, direction: 'horizontal', definition: 'Philosophie de vie de Bière-Chanel' },
{ word: 'SOPHIA', x: 24, y: 2, direction: 'vertical', definition: 'en retard même à son propre anniversaire' },
{ word: 'TT', x: 24, y: 11, direction: 'vertical', definition: 'Principal avantage à Mention' },
{ word: 'FUEL', x: 23, y: 21, direction: 'horizontal', definition: "Richesse d'NHST" },
{ word: 'OFFICE', x: 24, y: 20, direction: 'vertical', definition: 'On se retrouve tous pendant ses jours' },
{ word: 'DEBOUT', x: 25, y: 6, direction: 'vertical', definition: 'Position des daily, by the book' },
{ word: 'SQUAD', x: 24, y: 5, direction: 'vertical', definition: 'Equipe de mentionos' },
{ word: 'ISSOU', x: 25, y: 12, direction: 'vertical', definition: "Expression de El Risitas populaire chez les geek de Mention" },
{ word: 'VOYELLES', x: 24, y: 19, direction: 'horizontal', definition: 'Quentin les perds souvent' },
{ word: 'DATA', x: 25, y: 18, direction: 'vertical', definition: 'Le royaume de Xavier' },
{ word: 'OBSCUR', x: 25, y: 3, direction: 'horizontal', definition: 'Les règles autour de workspaces' },
{ word: 'ETIENNE', x: 25, y: 10, direction: 'horizontal', definition: 'Titi sans Grosminet' },
{ word: 'TATE', x: 26, y: 17, direction: 'vertical', definition: "Lucien s'est fait virer pour l'avoir fait" },
{ word: 'FR', x: 26, y: 19, direction: 'vertical', definition: 'Deuxième langue de l\'application' },
{ word: 'IA', x: 26, y: 23, direction: 'vertical', definition: "Alert Overview s'en sert" },
{ word: 'CS', x: 27, y: 2, direction: 'vertical', definition: 'En charge de gérer les Karen' },
{ word: 'ST', x: 26, y: 12, direction: 'horizontal', definition: "Quentin le porte en nom mais n'en est pas un" },
{ word: 'SQL', x: 27, y: 14, direction: 'vertical', definition: "Langage d'XPLR" },
{ word: 'TAFF', x: 26, y: 17, direction: 'horizontal', definition: "A la fin à Mention on en faisait plus trop" },
{ word: 'TISER', x: 26, y: 22, direction: 'horizontal', definition: "Activité préférée des mentionos" },
{ word: 'CHAUSSETTES', x: 27, y: 2, direction: 'horizontal', definition: "Florian ne les mets pas aux pieds" },
{ word: 'PATRICIA', x: 27, y: 16, direction: 'horizontal', definition: "Patty pour les intimes" },
{ word: 'UI', x: 28, y: 24, direction: 'vertical', definition: "Old school surtout sur le feed" },
{ word: 'SF', x: 28, y: 25, direction: 'vertical', definition: "Framework du backend" },
{ word: 'SI', x: 28, y: 2, direction: 'horizontal', definition: "La charge des alternants d'Antoine" },
{ word: 'QUOTA', x: 28, y: 14, direction: 'horizontal', definition: "Paramétrable depuis Chargebee" },
{ word: 'USD', x: 28, y: 24, direction: 'horizontal', definition: "Pour acheter Mention aux US" },
{ word: 'AUDREY', x: 29, y: 3, direction: 'horizontal', definition: "son arrivée est corrélée avec la fin de mention" },
{ word: 'SOUPLINE', x: 29, y: 10, direction: 'horizontal', definition: "Lissage de Pierre" },
{ word: 'BEN', x: 29, y: 19, direction: 'horizontal', definition: "Directeur mal-aimé du Marketing" },
{ word: 'GIF', x: 29, y: 23, direction: 'horizontal', definition: "Fichier animé qui enflammait notre Slack" }
]

export default cells;